#!/usr/bin/env python
"""Why an absolute contamination threshold does not work, in about forty lines.

Documentation that executes. Run it:

    python examples/contamination_demo.py

The argument in three measurements:

1. Score a corpus that **cannot** be contaminated — generated by the same
   grammar with a different seed — by the published rule. It comes out
   non-zero, and no lower than the genuine test split. The rule is measuring
   how formulaic the domain is.
2. Calibrate a threshold from that same disjoint corpus instead, and the clean
   split falls to zero.
3. Inject contamination at a known rate and watch the calibrated gate report
   approximately that rate back.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from dslm.corpus import contamination as contam
from dslm.corpus.curate import apply_curation, find_duplicates
from dslm.corpus.record import build_corpus
from dslm.corpus.split import split_corpus
from dslm.corpus.synth import PLANS, generate


def heading(text: str) -> None:
    print(f"\n{text}\n{'-' * len(text)}")


def main() -> int:
    corpus = generate(PLANS["main"])
    null = generate(PLANS["holdout"])
    cleaned = apply_curation(corpus, find_duplicates(corpus.records))
    split = split_corpus(cleaned, seed=1, curation=find_duplicates(cleaned.records))

    heading("1. The published rule, applied as published")
    disjoint = contam.contamination_report(split.train, null)
    genuine = contam.contamination_report(split.train, split.test)
    print(f"  the holdout corpus, which shares NO record with training: {disjoint.rate:.2%}")
    print(f"  the genuine test split, which might overlap it:           {genuine.rate:.2%}")
    print()
    print("  Data that cannot be contaminated does not score lower than data")
    print("  that might be. The rule cannot order the two, so a threshold on its")
    print("  output decides on noise. Maintenance write-ups are formulaic, and")
    print("  two unrelated work orders routinely share a thirteen-word run.")

    heading("2. Calibrate the threshold against the disjoint corpus instead")
    calibration = contam.calibrate(split.train, null, drop_shared=True)
    print(f"  {calibration.summary()}")
    if calibration.dropped:
        print(f"  ({calibration.dropped} null record(s) removed: the same grammar with a")
        print("   different seed really can produce the same sentence, and that is")
        print("   reported rather than hidden.)")
    clean = contam.contamination_report(split.train, split.test, calibration=calibration)
    print(f"  the clean split, at the calibrated threshold:             {clean.rate:.2%}")

    heading("3. Inject contamination at a known rate")
    print("  injected   measured")
    for rate in (0.0, 0.05, 0.10, 0.25):
        count = int(len(split.test) * rate)
        poisoned = build_corpus(
            [
                *list(split.test.records)[count:],
                *(
                    record.model_copy(update={"record_id": f"leak-{index:05d}"})
                    for index, record in enumerate(split.train.records[:count])
                ),
            ]
        )
        measured = contam.contamination_report(split.train, poisoned, calibration=calibration).rate
        print(f"  {rate:>7.0%}   {measured:>8.2%}")
    print()
    print("  Not a flag: an estimate of how much of the evaluation set the model")
    print("  has already seen. That is what makes the number worth acting on.")

    heading("And when there is no null corpus at all")
    try:
        contam.enforce(genuine)
    except Exception as exc:  # noqa: BLE001 - printing the refusal is the point
        print(f"  {exc}")
        print(f"  {getattr(exc, 'remedy', '')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
